#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_bookmarks import GrampsWebBookmarks
from gramps_web_mcp.api.api_client_chat import GrampsWebChat
from gramps_web_mcp.api.api_client_citations import GrampsWebCitations
from gramps_web_mcp.api.api_client_config import GrampsWebConfig
from gramps_web_mcp.api.api_client_dna import GrampsWebDna
from gramps_web_mcp.api.api_client_events import GrampsWebEvents
from gramps_web_mcp.api.api_client_exporters import GrampsWebExporters
from gramps_web_mcp.api.api_client_facts import GrampsWebFacts
from gramps_web_mcp.api.api_client_families import GrampsWebFamilies
from gramps_web_mcp.api.api_client_filters import GrampsWebFilters
from gramps_web_mcp.api.api_client_holidays import GrampsWebHolidays
from gramps_web_mcp.api.api_client_importers import GrampsWebImporters
from gramps_web_mcp.api.api_client_living import GrampsWebLiving
from gramps_web_mcp.api.api_client_media import GrampsWebMedia
from gramps_web_mcp.api.api_client_metadata import GrampsWebMetadata
from gramps_web_mcp.api.api_client_name_formats import GrampsWebNameFormats
from gramps_web_mcp.api.api_client_name_groups import GrampsWebNameGroups
from gramps_web_mcp.api.api_client_notes import GrampsWebNotes
from gramps_web_mcp.api.api_client_oidc import GrampsWebOidc
from gramps_web_mcp.api.api_client_people import GrampsWebPeople
from gramps_web_mcp.api.api_client_places import GrampsWebPlaces
from gramps_web_mcp.api.api_client_relations import GrampsWebRelations
from gramps_web_mcp.api.api_client_reports import GrampsWebReports
from gramps_web_mcp.api.api_client_repositories import GrampsWebRepositories
from gramps_web_mcp.api.api_client_search import GrampsWebSearch
from gramps_web_mcp.api.api_client_sources import GrampsWebSources
from gramps_web_mcp.api.api_client_tags import GrampsWebTags
from gramps_web_mcp.api.api_client_tasks import GrampsWebTasks
from gramps_web_mcp.api.api_client_timeline import GrampsWebTimeline
from gramps_web_mcp.api.api_client_token import GrampsWebToken
from gramps_web_mcp.api.api_client_transactions import GrampsWebTransactions
from gramps_web_mcp.api.api_client_translations import GrampsWebTranslations
from gramps_web_mcp.api.api_client_trees import GrampsWebTrees
from gramps_web_mcp.api.api_client_types import GrampsWebTypes
from gramps_web_mcp.api.api_client_users import GrampsWebUsers


class Api(
    GrampsWebBookmarks,
    GrampsWebChat,
    GrampsWebCitations,
    GrampsWebConfig,
    GrampsWebDna,
    GrampsWebEvents,
    GrampsWebExporters,
    GrampsWebFacts,
    GrampsWebFamilies,
    GrampsWebFilters,
    GrampsWebHolidays,
    GrampsWebImporters,
    GrampsWebLiving,
    GrampsWebMedia,
    GrampsWebMetadata,
    GrampsWebNameFormats,
    GrampsWebNameGroups,
    GrampsWebNotes,
    GrampsWebOidc,
    GrampsWebPeople,
    GrampsWebPlaces,
    GrampsWebRelations,
    GrampsWebReports,
    GrampsWebRepositories,
    GrampsWebSearch,
    GrampsWebSources,
    GrampsWebTags,
    GrampsWebTasks,
    GrampsWebTimeline,
    GrampsWebToken,
    GrampsWebTransactions,
    GrampsWebTranslations,
    GrampsWebTrees,
    GrampsWebTypes,
    GrampsWebUsers,
):
    """Composite Gramps Web API client — every domain client, one class."""

    __slots__ = ()
