#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_bookmarks import GrampsBookmarks
from gramps_mcp.api.api_client_chat import GrampsChat
from gramps_mcp.api.api_client_citations import GrampsCitations
from gramps_mcp.api.api_client_config import GrampsConfig
from gramps_mcp.api.api_client_dna import GrampsDna
from gramps_mcp.api.api_client_events import GrampsEvents
from gramps_mcp.api.api_client_exporters import GrampsExporters
from gramps_mcp.api.api_client_facts import GrampsFacts
from gramps_mcp.api.api_client_families import GrampsFamilies
from gramps_mcp.api.api_client_filters import GrampsFilters
from gramps_mcp.api.api_client_holidays import GrampsHolidays
from gramps_mcp.api.api_client_importers import GrampsImporters
from gramps_mcp.api.api_client_living import GrampsLiving
from gramps_mcp.api.api_client_media import GrampsMedia
from gramps_mcp.api.api_client_metadata import GrampsMetadata
from gramps_mcp.api.api_client_name_formats import GrampsNameFormats
from gramps_mcp.api.api_client_name_groups import GrampsNameGroups
from gramps_mcp.api.api_client_notes import GrampsNotes
from gramps_mcp.api.api_client_oidc import GrampsOidc
from gramps_mcp.api.api_client_people import GrampsPeople
from gramps_mcp.api.api_client_places import GrampsPlaces
from gramps_mcp.api.api_client_relations import GrampsRelations
from gramps_mcp.api.api_client_reports import GrampsReports
from gramps_mcp.api.api_client_repositories import GrampsRepositories
from gramps_mcp.api.api_client_search import GrampsSearch
from gramps_mcp.api.api_client_sources import GrampsSources
from gramps_mcp.api.api_client_tags import GrampsTags
from gramps_mcp.api.api_client_tasks import GrampsTasks
from gramps_mcp.api.api_client_timeline import GrampsTimeline
from gramps_mcp.api.api_client_token import GrampsToken
from gramps_mcp.api.api_client_transactions import GrampsTransactions
from gramps_mcp.api.api_client_translations import GrampsTranslations
from gramps_mcp.api.api_client_trees import GrampsTrees
from gramps_mcp.api.api_client_types import GrampsTypes
from gramps_mcp.api.api_client_users import GrampsUsers


class Api(
    GrampsBookmarks,
    GrampsChat,
    GrampsCitations,
    GrampsConfig,
    GrampsDna,
    GrampsEvents,
    GrampsExporters,
    GrampsFacts,
    GrampsFamilies,
    GrampsFilters,
    GrampsHolidays,
    GrampsImporters,
    GrampsLiving,
    GrampsMedia,
    GrampsMetadata,
    GrampsNameFormats,
    GrampsNameGroups,
    GrampsNotes,
    GrampsOidc,
    GrampsPeople,
    GrampsPlaces,
    GrampsRelations,
    GrampsReports,
    GrampsRepositories,
    GrampsSearch,
    GrampsSources,
    GrampsTags,
    GrampsTasks,
    GrampsTimeline,
    GrampsToken,
    GrampsTransactions,
    GrampsTranslations,
    GrampsTrees,
    GrampsTypes,
    GrampsUsers,
):
    """Composite Gramps API client — every domain client, one class."""

    __slots__ = ()
