#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebTranslations(GrampsWebApiBase):
    def get_translation(self, **kwargs) -> Response:
        """GET /translations/{language}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/translations/{language}",
            path_params=["language"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_translation(self, **kwargs) -> Response:
        """POST /translations/{language}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/translations/{language}",
            path_params=["language"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_translations(self, **kwargs) -> Response:
        """GET /translations/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/translations/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
