#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebMedia(GrampsWebApiBase):
    def get_media_object(self, **kwargs) -> Response:
        """GET /media/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/media/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_media_objects(self, **kwargs) -> Response:
        """POST /media/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/media/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_media(self, **kwargs) -> Response:
        """GET /media/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/media/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_media_file(self, **kwargs) -> Response:
        """GET /media/{handle}/file"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/media/{handle}/file",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_media_file(self, **kwargs) -> Response:
        """PUT /media/{handle}/file"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/media/{handle}/file",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_media_face_detection(self, **kwargs) -> Response:
        """GET /media/{handle}/face_detection"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/media/{handle}/face_detection",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_media_ocr(self, **kwargs) -> Response:
        """POST /media/{handle}/ocr"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/media/{handle}/ocr",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_media_archive(self, **kwargs) -> Response:
        """POST /media/archive/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/media/archive/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_media_archive_filename(self, **kwargs) -> Response:
        """GET /media/archive/{filename}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/media/archive/{filename}",
            path_params=["filename"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_media_archive_upload_zip(self, **kwargs) -> Response:
        """POST /media/archive/upload/zip"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/media/archive/upload/zip",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
