#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebNameFormats(GrampsWebApiBase):
    def get_name_formats(self, **kwargs) -> Response:
        """GET /name-formats/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/name-formats/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
