#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebTags(GrampsWebApiBase):
    def get_tag(self, **kwargs) -> Response:
        """GET /tags/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tags/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_tags(self, **kwargs) -> Response:
        """GET /tags/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tags/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
