#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebTrees(GrampsWebApiBase):
    def get_tree(self, **kwargs) -> Response:
        """GET /trees/{tree_id}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/trees/{tree_id}",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_tree(self, **kwargs) -> Response:
        """PUT /trees/{tree_id}"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/trees/{tree_id}",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_trees(self, **kwargs) -> Response:
        """GET /trees/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/trees/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_trees(self, **kwargs) -> Response:
        """POST /trees/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_disable_tree(self, **kwargs) -> Response:
        """POST /trees/{tree_id}/disable"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/{tree_id}/disable",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_enable_tree(self, **kwargs) -> Response:
        """POST /trees/{tree_id}/enable"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/{tree_id}/enable",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_repair_tree(self, **kwargs) -> Response:
        """POST /trees/{tree_id}/repair"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/{tree_id}/repair",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_migrate_tree(self, **kwargs) -> Response:
        """POST /trees/{tree_id}/migrate"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/{tree_id}/migrate",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_tree_config(self, **kwargs) -> Response:
        """GET /trees/{tree_id}/config"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/trees/{tree_id}/config",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_tree_config(self, **kwargs) -> Response:
        """PUT /trees/{tree_id}/config"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/trees/{tree_id}/config",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_verify(self, **kwargs) -> Response:
        """POST /trees/{tree_id}/verify"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/trees/{tree_id}/verify",
            path_params=["tree_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
