#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebPlaces(GrampsWebApiBase):
    def get_place(self, **kwargs) -> Response:
        """GET /places/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/places/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_places(self, **kwargs) -> Response:
        """GET /places/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/places/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_place(self, **kwargs) -> Response:
        """GET /places/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/places/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
