#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebConfig(GrampsWebApiBase):
    def get_configs(self, **kwargs) -> Response:
        """GET /config/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/config/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_config(self, **kwargs) -> Response:
        """DELETE /config/{key}/"""
        return self._call(
            http="DELETE",
            url_template="https://gramps.arpa/api/config/{key}/",
            path_params=["key"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_config(self, **kwargs) -> Response:
        """GET /config/{key}/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/config/{key}/",
            path_params=["key"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_config(self, **kwargs) -> Response:
        """PUT /config/{key}/"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/config/{key}/",
            path_params=["key"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
