#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebRepositories(GrampsWebApiBase):
    def get_repository(self, **kwargs) -> Response:
        """GET /repositories/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/repositories/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_repositories(self, **kwargs) -> Response:
        """GET /repositories/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/repositories/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_repository(self, **kwargs) -> Response:
        """GET /repositories/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/repositories/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
