#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebTasks(GrampsWebApiBase):
    def get_tasks(self, **kwargs) -> Response:
        """GET /tasks/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tasks/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_task(self, **kwargs) -> Response:
        """GET /tasks/{task_id}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tasks/{task_id}",
            path_params=["task_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
