#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_web_mcp.api.api_client_base import GrampsWebApiBase
from gramps_web_mcp.gramps_web_models import Response


class GrampsWebSearch(GrampsWebApiBase):
    def get_search(self, **kwargs) -> Response:
        """GET /search/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/search/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_search_index(self, **kwargs) -> Response:
        """POST /search/index/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/search/index/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
