"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_web_mcp.auth import get_client


def register_types_tools(mcp: FastMCP):
    @mcp.tool(tags={"types"})
    async def gramps_web_types(
        action: str = Field(
            description="Action to perform. One of: 'get_custom_type', 'get_custom_types', 'get_default_type_map', 'get_default_type', 'get_default_types', 'get_types'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web types operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_web_types action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_custom_type":
            return client.get_custom_type(**kwargs)
        elif action == "get_custom_types":
            return client.get_custom_types(**kwargs)
        elif action == "get_default_type_map":
            return client.get_default_type_map(**kwargs)
        elif action == "get_default_type":
            return client.get_default_type(**kwargs)
        elif action == "get_default_types":
            return client.get_default_types(**kwargs)
        elif action == "get_types":
            return client.get_types(**kwargs)
        raise ValueError(f"Unknown action: {action}")
