"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_web_mcp.auth import get_client


def register_importers_tools(mcp: FastMCP):
    @mcp.tool(tags={"importers"})
    async def gramps_web_importers(
        action: str = Field(
            description="Action to perform. One of: 'post_importer_file', 'get_importer', 'get_importers'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web importers operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_web_importers action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "post_importer_file":
            return client.post_importer_file(**kwargs)
        elif action == "get_importer":
            return client.get_importer(**kwargs)
        elif action == "get_importers":
            return client.get_importers(**kwargs)
        raise ValueError(f"Unknown action: {action}")
