"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_web_mcp.auth import get_client


def register_people_tools(mcp: FastMCP):
    @mcp.tool(tags={"people"})
    async def gramps_web_people(
        action: str = Field(
            description="Action to perform. One of: 'get_person', 'get_people', 'post_merge_person'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web people operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_web_people action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_person":
            return client.get_person(**kwargs)
        elif action == "get_people":
            return client.get_people(**kwargs)
        elif action == "post_merge_person":
            return client.post_merge_person(**kwargs)
        raise ValueError(f"Unknown action: {action}")
