"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_web_mcp.auth import get_client


def register_metadata_tools(mcp: FastMCP):
    @mcp.tool(tags={"metadata"})
    async def gramps_web_metadata(
        action: str = Field(
            description="Action to perform. One of: 'get_metadata', 'get_metadata_researcher', 'put_metadata_researcher'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web metadata operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_web_metadata action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_metadata":
            return client.get_metadata(**kwargs)
        elif action == "get_metadata_researcher":
            return client.get_metadata_researcher(**kwargs)
        elif action == "put_metadata_researcher":
            return client.put_metadata_researcher(**kwargs)
        raise ValueError(f"Unknown action: {action}")
