#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebHolidays(GrampsWebApiBase):
    def get_holiday(self, **kwargs) -> Response:
        """GET /holidays/{country}/{year}/{month}/{day}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/holidays/{country}/{year}/{month}/{day}",
            path_params=["country", "year", "month", "day"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_holidays(self, **kwargs) -> Response:
        """GET /holidays/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/holidays/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
