#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebToken(GrampsWebApiBase):
    def post_token(self, **kwargs) -> Response:
        """POST /token/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/token/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_token_refresh(self, **kwargs) -> Response:
        """POST /token/refresh/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/token/refresh/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_token_create_owner(self, **kwargs) -> Response:
        """GET /token/create_owner/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/token/create_owner/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_token_create_owner(self, **kwargs) -> Response:
        """POST /token/create_owner/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/token/create_owner/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
