#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsTags(GrampsApiBase):
    def get_tag(self, **kwargs) -> Response:
        """GET /tags/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tags/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_tags(self, **kwargs) -> Response:
        """GET /tags/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/tags/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
