#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsEvents(GrampsApiBase):
    def get_event_span(self, **kwargs) -> Response:
        """GET /events/{handle1}/span/{handle2}"""
        return self._call(
            http="GET",
            url_template="/api/events/{handle1}/span/{handle2}",
            path_params=["handle1", "handle2"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_event(self, **kwargs) -> Response:
        """GET /events/{handle}"""
        return self._call(
            http="GET",
            url_template="/api/events/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_events(self, **kwargs) -> Response:
        """GET /events/"""
        return self._call(
            http="GET",
            url_template="/api/events/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_event(self, **kwargs) -> Response:
        """GET /events/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="/api/events/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
