#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebTransactions(GrampsWebApiBase):
    def post_objects(self, **kwargs) -> Response:
        """POST /objects/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/objects/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_delete_objects(self, **kwargs) -> Response:
        """POST /objects/delete/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/objects/delete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_delete_objects_by_handle(self, **kwargs) -> Response:
        """POST /objects/delete-by-handle/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/objects/delete-by-handle/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_transactions(self, **kwargs) -> Response:
        """POST /transactions/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/transactions/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_transactions_history(self, **kwargs) -> Response:
        """GET /transactions/history/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/transactions/history/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_transaction_history(self, **kwargs) -> Response:
        """GET /transactions/history/{transaction_id}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/transactions/history/{transaction_id}",
            path_params=["transaction_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_transaction_undo(self, **kwargs) -> Response:
        """GET /transactions/history/{transaction_id}/undo"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/transactions/history/{transaction_id}/undo",
            path_params=["transaction_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_transaction_undo(self, **kwargs) -> Response:
        """POST /transactions/history/{transaction_id}/undo"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/transactions/history/{transaction_id}/undo",
            path_params=["transaction_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
