#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebChat(GrampsWebApiBase):
    def post_chat(self, **kwargs) -> Response:
        """POST /chat/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/chat/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
