#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsExporters(GrampsApiBase):
    def get_exporter_file(self, **kwargs) -> Response:
        """GET /exporters/{extension}/file"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/exporters/{extension}/file",
            path_params=["extension"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_exporter_file(self, **kwargs) -> Response:
        """POST /exporters/{extension}/file"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/exporters/{extension}/file",
            path_params=["extension"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_exporter_file_result(self, **kwargs) -> Response:
        """GET /exporters/{extension}/file/processed/{filename}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/exporters/{extension}/file/processed/{filename}",
            path_params=["extension", "filename"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_exporter(self, **kwargs) -> Response:
        """GET /exporters/{extension}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/exporters/{extension}",
            path_params=["extension"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_exporters(self, **kwargs) -> Response:
        """GET /exporters/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/exporters/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
