#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebReports(GrampsWebApiBase):
    def get_report_file(self, **kwargs) -> Response:
        """GET /reports/{report_id}/file"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/reports/{report_id}/file",
            path_params=["report_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_report_file(self, **kwargs) -> Response:
        """POST /reports/{report_id}/file"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/reports/{report_id}/file",
            path_params=["report_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_report(self, **kwargs) -> Response:
        """GET /reports/{report_id}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/reports/{report_id}",
            path_params=["report_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_reports(self, **kwargs) -> Response:
        """GET /reports/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/reports/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_report_file_result(self, **kwargs) -> Response:
        """GET /reports/{report_id}/file/processed/{filename}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/reports/{report_id}/file/processed/{filename}",
            path_params=["report_id", "filename"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
