#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebRelations(GrampsWebApiBase):
    def get_relation(self, **kwargs) -> Response:
        """GET /relations/{handle1}/{handle2}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/relations/{handle1}/{handle2}",
            path_params=["handle1", "handle2"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_relations(self, **kwargs) -> Response:
        """GET /relations/{handle1}/{handle2}/all"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/relations/{handle1}/{handle2}/all",
            path_params=["handle1", "handle2"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
