#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsSources(GrampsApiBase):
    def get_source(self, **kwargs) -> Response:
        """GET /sources/{handle}"""
        return self._call(
            http="GET",
            url_template="/api/sources/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_sources(self, **kwargs) -> Response:
        """GET /sources/"""
        return self._call(
            http="GET",
            url_template="/api/sources/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_source(self, **kwargs) -> Response:
        """GET /sources/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="/api/sources/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
