#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebOidc(GrampsWebApiBase):
    def get_oidcloginresource(self, **kwargs) -> Response:
        """GET /oidc/login/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/login/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_oidccallbackresource(self, **kwargs) -> Response:
        """GET /oidc/callback/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/callback/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_oidccallbackresource_provider(self, **kwargs) -> Response:
        """GET /oidc/callback/{provider_id}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/callback/{provider_id}",
            path_params=["provider_id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_oidcconfigresource(self, **kwargs) -> Response:
        """GET /oidc/config/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/config/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_oidctokenexchangeresource(self, **kwargs) -> Response:
        """GET /oidc/tokens/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/tokens/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_oidclogoutresource(self, **kwargs) -> Response:
        """GET /oidc/logout/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/oidc/logout/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_oidcbackchannellogoutresource(self, **kwargs) -> Response:
        """POST /oidc/backchannel-logout/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/oidc/backchannel-logout/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
