#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebNotes(GrampsWebApiBase):
    def get_note(self, **kwargs) -> Response:
        """GET /notes/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/notes/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_notes(self, **kwargs) -> Response:
        """GET /notes/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/notes/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_note(self, **kwargs) -> Response:
        """GET /notes/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/notes/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
