#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsNameGroups(GrampsApiBase):
    def get_set_name_group(self, **kwargs) -> Response:
        """GET /name-groups/{surname}/{group}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/name-groups/{surname}/{group}",
            path_params=["surname", "group"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_set_name_group(self, **kwargs) -> Response:
        """POST /name-groups/{surname}/{group}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/name-groups/{surname}/{group}",
            path_params=["surname", "group"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_get_name_group(self, **kwargs) -> Response:
        """GET /name-groups/{surname}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/name-groups/{surname}",
            path_params=["surname"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_get_name_group(self, **kwargs) -> Response:
        """POST /name-groups/{surname}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/name-groups/{surname}",
            path_params=["surname"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_name_groups(self, **kwargs) -> Response:
        """GET /name-groups/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/name-groups/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_name_groups(self, **kwargs) -> Response:
        """POST /name-groups/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/name-groups/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
