#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebTypes(GrampsWebApiBase):
    def get_custom_type(self, **kwargs) -> Response:
        """GET /types/custom/{datatype}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/custom/{datatype}",
            path_params=["datatype"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_custom_types(self, **kwargs) -> Response:
        """GET /types/custom/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/custom/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_default_type_map(self, **kwargs) -> Response:
        """GET /types/default/{datatype}/map"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/default/{datatype}/map",
            path_params=["datatype"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_default_type(self, **kwargs) -> Response:
        """GET /types/default/{datatype}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/default/{datatype}",
            path_params=["datatype"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_default_types(self, **kwargs) -> Response:
        """GET /types/default/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/default/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_types(self, **kwargs) -> Response:
        """GET /types/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/types/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
