#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsDna(GrampsApiBase):
    def get_person_dna_matches(self, **kwargs) -> Response:
        """GET /people/{handle}/dna/matches"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/people/{handle}/dna/matches",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_person_ydna(self, **kwargs) -> Response:
        """GET /people/{handle}/ydna"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/people/{handle}/ydna",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_dna_match_parser(self, **kwargs) -> Response:
        """POST /parsers/dna-match"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/parsers/dna-match",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
