#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebLiving(GrampsWebApiBase):
    def get_living_dates(self, **kwargs) -> Response:
        """GET /living/{handle}/dates"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/living/{handle}/dates",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_living(self, **kwargs) -> Response:
        """GET /living/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/living/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
