#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsFilters(GrampsApiBase):
    def delete_filter(self, **kwargs) -> Response:
        """DELETE /filters/{namespace}/{name}"""
        return self._call(
            http="DELETE",
            url_template="https://gramps.arpa/api/filters/{namespace}/{name}",
            path_params=["namespace", "name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_filter(self, **kwargs) -> Response:
        """GET /filters/{namespace}/{name}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/filters/{namespace}/{name}",
            path_params=["namespace", "name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_filters_namespace(self, **kwargs) -> Response:
        """GET /filters/{namespace}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/filters/{namespace}",
            path_params=["namespace"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_filters_namespace(self, **kwargs) -> Response:
        """POST /filters/{namespace}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/filters/{namespace}",
            path_params=["namespace"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_filters_namespace(self, **kwargs) -> Response:
        """PUT /filters/{namespace}"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/filters/{namespace}",
            path_params=["namespace"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_filters(self, **kwargs) -> Response:
        """GET /filters/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/filters/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
