#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebFamilies(GrampsWebApiBase):
    def get_family(self, **kwargs) -> Response:
        """GET /families/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/families/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_families(self, **kwargs) -> Response:
        """POST /families/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/families/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_families(self, **kwargs) -> Response:
        """GET /families/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/families/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_merge_family(self, **kwargs) -> Response:
        """POST /families/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/families/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
