#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsNameFormats(GrampsApiBase):
    def get_name_formats(self, **kwargs) -> Response:
        """GET /name-formats/"""
        return self._call(
            http="GET",
            url_template="/api/name-formats/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
