#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebBookmarks(GrampsWebApiBase):
    def get_bookmark(self, **kwargs) -> Response:
        """GET /bookmarks/{namespace}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/bookmarks/{namespace}",
            path_params=["namespace"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_bookmarks(self, **kwargs) -> Response:
        """GET /bookmarks/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/bookmarks/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_bookmark_edit(self, **kwargs) -> Response:
        """DELETE /bookmarks/{namespace}/{handle}"""
        return self._call(
            http="DELETE",
            url_template="https://gramps.arpa/api/bookmarks/{namespace}/{handle}",
            path_params=["namespace", "handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_bookmark_edit(self, **kwargs) -> Response:
        """PUT /bookmarks/{namespace}/{handle}"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/bookmarks/{namespace}/{handle}",
            path_params=["namespace", "handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
