#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebFacts(GrampsWebApiBase):
    def get_facts(self, **kwargs) -> Response:
        """GET /facts/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/facts/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
