#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsPeople(GrampsApiBase):
    def get_person(self, **kwargs) -> Response:
        """GET /people/{handle}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/people/{handle}",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_people(self, **kwargs) -> Response:
        """GET /people/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/people/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_merge_person(self, **kwargs) -> Response:
        """POST /people/{phoenix_handle}/merge/{titanic_handle}"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/people/{phoenix_handle}/merge/{titanic_handle}",
            path_params=["phoenix_handle", "titanic_handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
