#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebImporters(GrampsWebApiBase):
    def post_importer_file(self, **kwargs) -> Response:
        """POST /importers/{extension}/file"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/importers/{extension}/file",
            path_params=["extension"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_importer(self, **kwargs) -> Response:
        """GET /importers/{extension}"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/importers/{extension}",
            path_params=["extension"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_importers(self, **kwargs) -> Response:
        """GET /importers/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/importers/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
