#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebUsers(GrampsWebApiBase):
    def get_users(self, **kwargs) -> Response:
        """GET /users/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/users/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_users(self, **kwargs) -> Response:
        """POST /users/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_user(self, **kwargs) -> Response:
        """DELETE /users/{user_name}/"""
        return self._call(
            http="DELETE",
            url_template="https://gramps.arpa/api/users/{user_name}/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_user(self, **kwargs) -> Response:
        """GET /users/{user_name}/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/users/{user_name}/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_user(self, **kwargs) -> Response:
        """POST /users/{user_name}/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/{user_name}/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_user(self, **kwargs) -> Response:
        """PUT /users/{user_name}/"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/users/{user_name}/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_register(self, **kwargs) -> Response:
        """POST /users/{user_name}/register/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/{user_name}/register/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_user_create_owner(self, **kwargs) -> Response:
        """POST /users/{user_name}/create_owner/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/{user_name}/create_owner/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_confirm_email(self, **kwargs) -> Response:
        """GET /users/-/email/confirm/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/users/-/email/confirm/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_change_password(self, **kwargs) -> Response:
        """POST /users/{user_name}/password/change"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/{user_name}/password/change",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_reset_password(self, **kwargs) -> Response:
        """GET /users/-/password/reset/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/users/-/password/reset/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_reset_password(self, **kwargs) -> Response:
        """POST /users/-/password/reset/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/-/password/reset/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_trigger_reset_password(self, **kwargs) -> Response:
        """POST /users/{user_name}/password/reset/trigger/"""
        return self._call(
            http="POST",
            url_template="https://gramps.arpa/api/users/{user_name}/password/reset/trigger/",
            path_params=["user_name"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
