#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsWebApiBase
from gramps_mcp.gramps_models import Response


class GrampsWebMetadata(GrampsWebApiBase):
    def get_metadata(self, **kwargs) -> Response:
        """GET /metadata/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/metadata/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_metadata_researcher(self, **kwargs) -> Response:
        """GET /metadata/researcher/"""
        return self._call(
            http="GET",
            url_template="https://gramps.arpa/api/metadata/researcher/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def put_metadata_researcher(self, **kwargs) -> Response:
        """PUT /metadata/researcher/"""
        return self._call(
            http="PUT",
            url_template="https://gramps.arpa/api/metadata/researcher/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
