#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.api.api_client_base import GrampsApiBase
from gramps_mcp.gramps_models import Response


class GrampsTimeline(GrampsApiBase):
    def get_person_timeline(self, **kwargs) -> Response:
        """GET /people/{handle}/timeline"""
        return self._call(
            http="GET",
            url_template="/api/people/{handle}/timeline",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_family_timeline(self, **kwargs) -> Response:
        """GET /families/{handle}/timeline"""
        return self._call(
            http="GET",
            url_template="/api/families/{handle}/timeline",
            path_params=["handle"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_timeline_people(self, **kwargs) -> Response:
        """GET /timelines/people/"""
        return self._call(
            http="GET",
            url_template="/api/timelines/people/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_timeline_families(self, **kwargs) -> Response:
        """GET /timelines/families/"""
        return self._call(
            http="GET",
            url_template="/api/timelines/families/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
