"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from gramps_mcp.mcp.mcp_bookmarks import register_bookmarks_tools
from gramps_mcp.mcp.mcp_chat import register_chat_tools
from gramps_mcp.mcp.mcp_citations import register_citations_tools
from gramps_mcp.mcp.mcp_config import register_config_tools
from gramps_mcp.mcp.mcp_dna import register_dna_tools
from gramps_mcp.mcp.mcp_events import register_events_tools
from gramps_mcp.mcp.mcp_exporters import register_exporters_tools
from gramps_mcp.mcp.mcp_facts import register_facts_tools
from gramps_mcp.mcp.mcp_families import register_families_tools
from gramps_mcp.mcp.mcp_filters import register_filters_tools
from gramps_mcp.mcp.mcp_holidays import register_holidays_tools
from gramps_mcp.mcp.mcp_importers import register_importers_tools
from gramps_mcp.mcp.mcp_kg import register_kg_tools
from gramps_mcp.mcp.mcp_living import register_living_tools
from gramps_mcp.mcp.mcp_media import register_media_tools
from gramps_mcp.mcp.mcp_metadata import register_metadata_tools
from gramps_mcp.mcp.mcp_name_formats import register_name_formats_tools
from gramps_mcp.mcp.mcp_name_groups import register_name_groups_tools
from gramps_mcp.mcp.mcp_notes import register_notes_tools
from gramps_mcp.mcp.mcp_oidc import register_oidc_tools
from gramps_mcp.mcp.mcp_people import register_people_tools
from gramps_mcp.mcp.mcp_places import register_places_tools
from gramps_mcp.mcp.mcp_relations import register_relations_tools
from gramps_mcp.mcp.mcp_reports import register_reports_tools
from gramps_mcp.mcp.mcp_repositories import register_repositories_tools
from gramps_mcp.mcp.mcp_search import register_search_tools
from gramps_mcp.mcp.mcp_sources import register_sources_tools
from gramps_mcp.mcp.mcp_tags import register_tags_tools
from gramps_mcp.mcp.mcp_tasks import register_tasks_tools
from gramps_mcp.mcp.mcp_timeline import register_timeline_tools
from gramps_mcp.mcp.mcp_token import register_token_tools
from gramps_mcp.mcp.mcp_transactions import register_transactions_tools
from gramps_mcp.mcp.mcp_translations import register_translations_tools
from gramps_mcp.mcp.mcp_trees import register_trees_tools
from gramps_mcp.mcp.mcp_types import register_types_tools
from gramps_mcp.mcp.mcp_users import register_users_tools

# (tag, toggle_env_var, register_fn) — consumed by mcp_server.get_mcp_instance().
TOOL_REGISTRY = [
    ("bookmarks", "BOOKMARKSTOOL", register_bookmarks_tools),
    ("chat", "CHATTOOL", register_chat_tools),
    ("citations", "CITATIONSTOOL", register_citations_tools),
    ("config", "CONFIGTOOL", register_config_tools),
    ("dna", "DNATOOL", register_dna_tools),
    ("events", "EVENTSTOOL", register_events_tools),
    ("exporters", "EXPORTERSTOOL", register_exporters_tools),
    ("facts", "FACTSTOOL", register_facts_tools),
    ("families", "FAMILIESTOOL", register_families_tools),
    ("filters", "FILTERSTOOL", register_filters_tools),
    ("holidays", "HOLIDAYSTOOL", register_holidays_tools),
    ("importers", "IMPORTERSTOOL", register_importers_tools),
    ("kg", "KGTOOL", register_kg_tools),
    ("living", "LIVINGTOOL", register_living_tools),
    ("media", "MEDIATOOL", register_media_tools),
    ("metadata", "METADATATOOL", register_metadata_tools),
    ("name_formats", "NAME_FORMATSTOOL", register_name_formats_tools),
    ("name_groups", "NAME_GROUPSTOOL", register_name_groups_tools),
    ("notes", "NOTESTOOL", register_notes_tools),
    ("oidc", "OIDCTOOL", register_oidc_tools),
    ("people", "PEOPLETOOL", register_people_tools),
    ("places", "PLACESTOOL", register_places_tools),
    ("relations", "RELATIONSTOOL", register_relations_tools),
    ("reports", "REPORTSTOOL", register_reports_tools),
    ("repositories", "REPOSITORIESTOOL", register_repositories_tools),
    ("search", "SEARCHTOOL", register_search_tools),
    ("sources", "SOURCESTOOL", register_sources_tools),
    ("tags", "TAGSTOOL", register_tags_tools),
    ("tasks", "TASKSTOOL", register_tasks_tools),
    ("timeline", "TIMELINETOOL", register_timeline_tools),
    ("token", "TOKENTOOL", register_token_tools),
    ("transactions", "TRANSACTIONSTOOL", register_transactions_tools),
    ("translations", "TRANSLATIONSTOOL", register_translations_tools),
    ("trees", "TREESTOOL", register_trees_tools),
    ("types", "TYPESTOOL", register_types_tools),
    ("users", "USERSTOOL", register_users_tools),
]

__all__ = [
    "register_bookmarks_tools",
    "register_chat_tools",
    "register_citations_tools",
    "register_config_tools",
    "register_dna_tools",
    "register_events_tools",
    "register_exporters_tools",
    "register_facts_tools",
    "register_families_tools",
    "register_filters_tools",
    "register_holidays_tools",
    "register_importers_tools",
    "register_kg_tools",
    "register_living_tools",
    "register_media_tools",
    "register_metadata_tools",
    "register_name_formats_tools",
    "register_name_groups_tools",
    "register_notes_tools",
    "register_oidc_tools",
    "register_people_tools",
    "register_places_tools",
    "register_relations_tools",
    "register_reports_tools",
    "register_repositories_tools",
    "register_search_tools",
    "register_sources_tools",
    "register_tags_tools",
    "register_tasks_tools",
    "register_timeline_tools",
    "register_token_tools",
    "register_transactions_tools",
    "register_translations_tools",
    "register_trees_tools",
    "register_types_tools",
    "register_users_tools",
    "TOOL_REGISTRY",
]
