"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_media_tools(mcp: FastMCP):
    @mcp.tool(tags={"media"})
    async def gramps_media(
        action: str = Field(
            description="Action to perform. One of: 'get_media_object', 'post_media_objects', 'get_media_objects', 'get_merge_media', 'get_media_file', 'put_media_file', 'get_media_face_detection', 'post_media_ocr', 'post_media_archive', 'get_media_archive_filename', 'post_media_archive_upload_zip'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps media operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_media action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_media_object":
            return client.get_media_object(**kwargs)
        elif action == "post_media_objects":
            return client.post_media_objects(**kwargs)
        elif action == "get_media_objects":
            return client.get_media_objects(**kwargs)
        elif action == "get_merge_media":
            return client.get_merge_media(**kwargs)
        elif action == "get_media_file":
            return client.get_media_file(**kwargs)
        elif action == "put_media_file":
            return client.put_media_file(**kwargs)
        elif action == "get_media_face_detection":
            return client.get_media_face_detection(**kwargs)
        elif action == "post_media_ocr":
            return client.post_media_ocr(**kwargs)
        elif action == "post_media_archive":
            return client.post_media_archive(**kwargs)
        elif action == "get_media_archive_filename":
            return client.get_media_archive_filename(**kwargs)
        elif action == "post_media_archive_upload_zip":
            return client.post_media_archive_upload_zip(**kwargs)
        raise ValueError(f"Unknown action: {action}")
