"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_filters_tools(mcp: FastMCP):
    @mcp.tool(tags={"filters"})
    async def gramps_filters(
        action: str = Field(
            description="Action to perform. One of: 'delete_filter', 'get_filter', 'get_filters_namespace', 'post_filters_namespace', 'put_filters_namespace', 'get_filters'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps filters operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_filters action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "delete_filter":
            return client.delete_filter(**kwargs)
        elif action == "get_filter":
            return client.get_filter(**kwargs)
        elif action == "get_filters_namespace":
            return client.get_filters_namespace(**kwargs)
        elif action == "post_filters_namespace":
            return client.post_filters_namespace(**kwargs)
        elif action == "put_filters_namespace":
            return client.put_filters_namespace(**kwargs)
        elif action == "get_filters":
            return client.get_filters(**kwargs)
        raise ValueError(f"Unknown action: {action}")
