"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_events_tools(mcp: FastMCP):
    @mcp.tool(tags={"events"})
    async def gramps_events(
        action: str = Field(
            description="Action to perform. One of: 'get_event_span', 'get_event', 'get_events', 'get_merge_event'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web events operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_events action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_event_span":
            return client.get_event_span(**kwargs)
        elif action == "get_event":
            return client.get_event(**kwargs)
        elif action == "get_events":
            return client.get_events(**kwargs)
        elif action == "get_merge_event":
            return client.get_merge_event(**kwargs)
        raise ValueError(f"Unknown action: {action}")
