"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_exporters_tools(mcp: FastMCP):
    @mcp.tool(tags={"exporters"})
    async def gramps_exporters(
        action: str = Field(
            description="Action to perform. One of: 'get_exporter_file', 'post_exporter_file', 'get_exporter_file_result', 'get_exporter', 'get_exporters'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps exporters operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_exporters action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_exporter_file":
            return client.get_exporter_file(**kwargs)
        elif action == "post_exporter_file":
            return client.post_exporter_file(**kwargs)
        elif action == "get_exporter_file_result":
            return client.get_exporter_file_result(**kwargs)
        elif action == "get_exporter":
            return client.get_exporter(**kwargs)
        elif action == "get_exporters":
            return client.get_exporters(**kwargs)
        raise ValueError(f"Unknown action: {action}")
