"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

import json
from typing import Any

from agent_utilities.mcp.action_dispatch import resolve_action
from agent_utilities.mcp.concurrency import run_blocking
from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_families_tools(mcp: FastMCP):
    @mcp.tool(tags={"families"})
    async def gramps_families(
        action: str = Field(
            description="Action to perform. One of: 'get_family', 'post_families', 'get_families', 'post_merge_family'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps families operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info("Executing Gramps families operation")

        if len(params_json.encode("utf-8")) > 1_048_576:
            return {"error": "params_json exceeds the connector limit"}
        try:
            kwargs = json.loads(params_json) if params_json else {}
        except (TypeError, ValueError):
            return {"error": "Invalid params_json"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}
        resolved = resolve_action(
            action,
            {
                "get_family",
                "post_families",
                "get_families",
                "post_merge_family",
            },
            service="gramps",
        )
        if isinstance(resolved, dict):
            return resolved
        method = getattr(client, resolved, None)
        if method is None:
            return {"error": "Unknown action"}
        return await run_blocking(method, **kwargs)
