"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

import json
from typing import Any

from agent_utilities.mcp.action_dispatch import resolve_action
from agent_utilities.mcp.concurrency import run_blocking
from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_users_tools(mcp: FastMCP):
    @mcp.tool(tags={"users"})
    async def gramps_users(
        action: str = Field(
            description="Action to perform. One of: 'get_users', 'post_users', 'delete_user', 'get_user', 'post_user', 'put_user', 'post_register', 'post_user_create_owner', 'get_confirm_email', 'post_change_password', 'get_reset_password', 'post_reset_password', 'post_trigger_reset_password'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps users operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info("Executing Gramps users operation")

        if len(params_json.encode("utf-8")) > 1_048_576:
            return {"error": "params_json exceeds the connector limit"}
        try:
            kwargs = json.loads(params_json) if params_json else {}
        except (TypeError, ValueError):
            return {"error": "Invalid params_json"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}
        resolved = resolve_action(
            action,
            {
                "get_users",
                "post_users",
                "delete_user",
                "get_user",
                "post_user",
                "put_user",
                "post_register",
                "post_user_create_owner",
                "get_confirm_email",
                "post_change_password",
                "get_reset_password",
                "post_reset_password",
                "post_trigger_reset_password",
            },
            service="gramps",
        )
        if isinstance(resolved, dict):
            return resolved
        method = getattr(client, resolved, None)
        if method is None:
            return {"error": "Unknown action"}
        return await run_blocking(method, **kwargs)
