"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_places_tools(mcp: FastMCP):
    @mcp.tool(tags={"places"})
    async def gramps_places(
        action: str = Field(
            description="Action to perform. One of: 'get_place', 'get_places', 'get_merge_place'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps places operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_places action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_place":
            return client.get_place(**kwargs)
        elif action == "get_places":
            return client.get_places(**kwargs)
        elif action == "get_merge_place":
            return client.get_merge_place(**kwargs)
        raise ValueError(f"Unknown action: {action}")
