"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_families_tools(mcp: FastMCP):
    @mcp.tool(tags={"families"})
    async def gramps_families(
        action: str = Field(
            description="Action to perform. One of: 'get_family', 'post_families', 'get_families', 'post_merge_family'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps families operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_families action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_family":
            return client.get_family(**kwargs)
        elif action == "post_families":
            return client.post_families(**kwargs)
        elif action == "get_families":
            return client.get_families(**kwargs)
        elif action == "post_merge_family":
            return client.post_merge_family(**kwargs)
        raise ValueError(f"Unknown action: {action}")
