"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_timeline_tools(mcp: FastMCP):
    @mcp.tool(tags={"timeline"})
    async def gramps_timeline(
        action: str = Field(
            description="Action to perform. One of: 'get_person_timeline', 'get_family_timeline', 'get_timeline_people', 'get_timeline_families'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web timeline operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_timeline action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_person_timeline":
            return client.get_person_timeline(**kwargs)
        elif action == "get_family_timeline":
            return client.get_family_timeline(**kwargs)
        elif action == "get_timeline_people":
            return client.get_timeline_people(**kwargs)
        elif action == "get_timeline_families":
            return client.get_timeline_families(**kwargs)
        raise ValueError(f"Unknown action: {action}")
