"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_users_tools(mcp: FastMCP):
    @mcp.tool(tags={"users"})
    async def gramps_users(
        action: str = Field(
            description="Action to perform. One of: 'get_users', 'post_users', 'delete_user', 'get_user', 'post_user', 'put_user', 'post_register', 'post_user_create_owner', 'get_confirm_email', 'post_change_password', 'get_reset_password', 'post_reset_password', 'post_trigger_reset_password'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web users operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_users action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_users":
            return client.get_users(**kwargs)
        elif action == "post_users":
            return client.post_users(**kwargs)
        elif action == "delete_user":
            return client.delete_user(**kwargs)
        elif action == "get_user":
            return client.get_user(**kwargs)
        elif action == "post_user":
            return client.post_user(**kwargs)
        elif action == "put_user":
            return client.put_user(**kwargs)
        elif action == "post_register":
            return client.post_register(**kwargs)
        elif action == "post_user_create_owner":
            return client.post_user_create_owner(**kwargs)
        elif action == "get_confirm_email":
            return client.get_confirm_email(**kwargs)
        elif action == "post_change_password":
            return client.post_change_password(**kwargs)
        elif action == "get_reset_password":
            return client.get_reset_password(**kwargs)
        elif action == "post_reset_password":
            return client.post_reset_password(**kwargs)
        elif action == "post_trigger_reset_password":
            return client.post_trigger_reset_password(**kwargs)
        raise ValueError(f"Unknown action: {action}")
