"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_sources_tools(mcp: FastMCP):
    @mcp.tool(tags={"sources"})
    async def gramps_sources(
        action: str = Field(
            description="Action to perform. One of: 'get_source', 'get_sources', 'get_merge_source'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps sources operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_sources action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_source":
            return client.get_source(**kwargs)
        elif action == "get_sources":
            return client.get_sources(**kwargs)
        elif action == "get_merge_source":
            return client.get_merge_source(**kwargs)
        raise ValueError(f"Unknown action: {action}")
