"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_reports_tools(mcp: FastMCP):
    @mcp.tool(tags={"reports"})
    async def gramps_reports(
        action: str = Field(
            description="Action to perform. One of: 'get_report_file', 'post_report_file', 'get_report', 'get_reports', 'get_report_file_result'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps reports operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_reports action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_report_file":
            return client.get_report_file(**kwargs)
        elif action == "post_report_file":
            return client.post_report_file(**kwargs)
        elif action == "get_report":
            return client.get_report(**kwargs)
        elif action == "get_reports":
            return client.get_reports(**kwargs)
        elif action == "get_report_file_result":
            return client.get_report_file_result(**kwargs)
        raise ValueError(f"Unknown action: {action}")
