"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_name_groups_tools(mcp: FastMCP):
    @mcp.tool(tags={"name-groups"})
    async def gramps_name_groups(
        action: str = Field(
            description="Action to perform. One of: 'get_set_name_group', 'post_set_name_group', 'get_get_name_group', 'post_get_name_group', 'get_name_groups', 'post_name_groups'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps name groups operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_name_groups action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_set_name_group":
            return client.get_set_name_group(**kwargs)
        elif action == "post_set_name_group":
            return client.post_set_name_group(**kwargs)
        elif action == "get_get_name_group":
            return client.get_get_name_group(**kwargs)
        elif action == "post_get_name_group":
            return client.post_get_name_group(**kwargs)
        elif action == "get_name_groups":
            return client.get_name_groups(**kwargs)
        elif action == "post_name_groups":
            return client.post_name_groups(**kwargs)
        raise ValueError(f"Unknown action: {action}")
