"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_oidc_tools(mcp: FastMCP):
    @mcp.tool(tags={"oidc"})
    async def gramps_oidc(
        action: str = Field(
            description="Action to perform. One of: 'get_oidcloginresource', 'get_oidccallbackresource', 'get_oidccallbackresource_provider', 'get_oidcconfigresource', 'get_oidctokenexchangeresource', 'get_oidclogoutresource', 'post_oidcbackchannellogoutresource'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web oidc operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_oidc action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_oidcloginresource":
            return client.get_oidcloginresource(**kwargs)
        elif action == "get_oidccallbackresource":
            return client.get_oidccallbackresource(**kwargs)
        elif action == "get_oidccallbackresource_provider":
            return client.get_oidccallbackresource_provider(**kwargs)
        elif action == "get_oidcconfigresource":
            return client.get_oidcconfigresource(**kwargs)
        elif action == "get_oidctokenexchangeresource":
            return client.get_oidctokenexchangeresource(**kwargs)
        elif action == "get_oidclogoutresource":
            return client.get_oidclogoutresource(**kwargs)
        elif action == "post_oidcbackchannellogoutresource":
            return client.post_oidcbackchannellogoutresource(**kwargs)
        raise ValueError(f"Unknown action: {action}")
