"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_transactions_tools(mcp: FastMCP):
    @mcp.tool(tags={"transactions"})
    async def gramps_transactions(
        action: str = Field(
            description="Action to perform. One of: 'post_objects', 'post_delete_objects', 'post_delete_objects_by_handle', 'post_transactions', 'get_transactions_history', 'get_transaction_history', 'get_transaction_undo', 'post_transaction_undo'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps transactions operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_transactions action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "post_objects":
            return client.post_objects(**kwargs)
        elif action == "post_delete_objects":
            return client.post_delete_objects(**kwargs)
        elif action == "post_delete_objects_by_handle":
            return client.post_delete_objects_by_handle(**kwargs)
        elif action == "post_transactions":
            return client.post_transactions(**kwargs)
        elif action == "get_transactions_history":
            return client.get_transactions_history(**kwargs)
        elif action == "get_transaction_history":
            return client.get_transaction_history(**kwargs)
        elif action == "get_transaction_undo":
            return client.get_transaction_undo(**kwargs)
        elif action == "post_transaction_undo":
            return client.post_transaction_undo(**kwargs)
        raise ValueError(f"Unknown action: {action}")
