"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

import json
from typing import Any

from agent_utilities.mcp.action_dispatch import resolve_action
from agent_utilities.mcp.concurrency import run_blocking
from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_media_tools(mcp: FastMCP):
    @mcp.tool(tags={"media"})
    async def gramps_media(
        action: str = Field(
            description="Action to perform. One of: 'get_media_object', 'post_media_objects', 'get_media_objects', 'get_merge_media', 'get_media_file', 'put_media_file', 'get_media_face_detection', 'post_media_ocr', 'post_media_archive', 'get_media_archive_filename', 'post_media_archive_upload_zip'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps media operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info("Executing Gramps media operation")

        if len(params_json.encode("utf-8")) > 1_048_576:
            return {"error": "params_json exceeds the connector limit"}
        try:
            kwargs = json.loads(params_json) if params_json else {}
        except (TypeError, ValueError):
            return {"error": "Invalid params_json"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}
        resolved = resolve_action(
            action,
            {
                "get_media_object",
                "post_media_objects",
                "get_media_objects",
                "get_merge_media",
                "get_media_file",
                "put_media_file",
                "get_media_face_detection",
                "post_media_ocr",
                "post_media_archive",
                "get_media_archive_filename",
                "post_media_archive_upload_zip",
            },
            service="gramps",
        )
        if isinstance(resolved, dict):
            return resolved
        method = getattr(client, resolved, None)
        if method is None:
            return {"error": "Unknown action"}
        return await run_blocking(method, **kwargs)
