"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_trees_tools(mcp: FastMCP):
    @mcp.tool(tags={"trees"})
    async def gramps_trees(
        action: str = Field(
            description="Action to perform. One of: 'get_tree', 'put_tree', 'get_trees', 'post_trees', 'post_disable_tree', 'post_enable_tree', 'post_repair_tree', 'post_migrate_tree', 'get_tree_config', 'put_tree_config', 'post_verify'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps trees operations. CONCEPT:GM-OS.identity.grmp."""
        if ctx:
            await ctx.info(f"Executing gramps_trees action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_tree":
            return client.get_tree(**kwargs)
        elif action == "put_tree":
            return client.put_tree(**kwargs)
        elif action == "get_trees":
            return client.get_trees(**kwargs)
        elif action == "post_trees":
            return client.post_trees(**kwargs)
        elif action == "post_disable_tree":
            return client.post_disable_tree(**kwargs)
        elif action == "post_enable_tree":
            return client.post_enable_tree(**kwargs)
        elif action == "post_repair_tree":
            return client.post_repair_tree(**kwargs)
        elif action == "post_migrate_tree":
            return client.post_migrate_tree(**kwargs)
        elif action == "get_tree_config":
            return client.get_tree_config(**kwargs)
        elif action == "put_tree_config":
            return client.put_tree_config(**kwargs)
        elif action == "post_verify":
            return client.post_verify(**kwargs)
        raise ValueError(f"Unknown action: {action}")
