"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from gramps_mcp.auth import get_client


def register_token_tools(mcp: FastMCP):
    @mcp.tool(tags={"token"})
    async def gramps_token(
        action: str = Field(
            description="Action to perform. One of: 'post_token', 'post_token_refresh', 'get_token_create_owner', 'post_token_create_owner'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage Gramps Web token operations. CONCEPT:GRMP-001."""
        if ctx:
            await ctx.info(f"Executing gramps_token action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "post_token":
            return client.post_token(**kwargs)
        elif action == "post_token_refresh":
            return client.post_token_refresh(**kwargs)
        elif action == "get_token_create_owner":
            return client.get_token_create_owner(**kwargs)
        elif action == "post_token_create_owner":
            return client.post_token_create_owner(**kwargs)
        raise ValueError(f"Unknown action: {action}")
